trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  # The Snyk extension requires npm; this just proves that it is pre-installed on this particular image.
  - script: |
      npm -v
      node -v
    displayName: 'show npm version'

  # The Snyk extension requires that you build your project first so it can best assess the dependency tree.
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'

  # You might prefer to use the `restore` option of .NET core rather than `build`. Either should suffice for Snyk to work
  # Uncomment the following if you prefer to use `restore` over `build`:
#  - task: DotNetCoreCLI@2
#    inputs:
#      command: 'restore'
#      feedsToUse: 'select'

  - task: SnykSecurityScan@0
    inputs:
      serviceConnectionEndpoint: 'my-snyk-token' # Replace this with your own service connection name
      testType: 'app'
      monitorOnBuild: true
      failOnIssues: true
