# Configure SNYK_TOKEN environment variable in your TravisCI project settings

language: java

script:
    - npm install -g snyk
    - snyk monitor --reachable-vulns # Enable reachable vulns, scan and publish results to Snyk
    - snyk test --reachable-vulns # Enable reachable vulns